name: Build

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Desactivar shallow clones para un análisis más relevante
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Necesario para obtener info del PR, si existe
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker:
    name: Docker Deployment
    runs-on: ubuntu-latest
    needs: sonarcloud  # Este job se ejecutará después de sonarcloud
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: shirleyascencio/as221s6_t06_cryptopay-frontend:latest
          push: true

      - name: Build and push database image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.database
          tags: shirleyascencio/as221s6_t06_cryptopay-database:latest
          push: true

      - name: Deploy using Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
